name: Benchmarking
on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  benchmark:
    name: Continuous benchmarking
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{github.sha}} ${{github.ref}}"
      - uses: actions/checkout@v4
      - run: git rev-parse HEAD
      - run: echo "${{github.sha}} ${{github.ref}}"
      - uses: actions/checkout@v4
        with:
          ref: master
      - run: git rev-parse HEAD
      - run: echo "${{github.sha}} ${{github.ref}}"

